---
- name: Build Java app and transfer to Docker instance
  hosts: app_instance
  become: yes
  tasks:
    - name: Install required packages
      apt:
        pkg:
          - git
          - openjdk-11-jdk
          - maven
        state: present
        update_cache: yes

    - name: Clone the Java app repository
      git:
        repo: 'https://github.com/vir2ozz/certask.git'
        dest: '/opt/certask'

    - name: Build the Java app using Maven
      command: mvn clean install -DskipTests
      args:
        chdir: /opt/certask

    - name: Transfer the built app to the Docker instance
      synchronize:
        src: /opt/certask/target/hello-1.0.war
        dest: /opt/hello-1.0.war
      delegate_to: docker_instance

- name: Create Docker image and run container
  hosts: docker_instance
  become: yes
  tasks:
    - name: Install Docker
      ansible.builtin.package:
        name: docker.io
        state: present
      become: true

    - name: Start and enable Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: Copy Dockerfile
      copy:
        src: Dockerfile
        dest: /opt/Dockerfile

    - name: Build Docker image
      command: docker build -t hello-1.0 /opt

    - name: Run Docker container
      command: docker run -d -p 8080:8080 --name hello-container hello-1.0
