---
- name: Build Java App
  hosts: java_builder
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk-devel
        state: present

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Clone repository
      git:
        repo: 'https://github.com/vir2ozz/certask.git'
        dest: /home/ec2-user/certask

    - name: Build Java app
      command: mvn clean package -f /home/ec2-user/certask/pom.xml

    - name: Copy WAR file to App Instance
      synchronize:
        src: /home/ec2-user/certask/target/hello-1.0.war
        dest: /home/ec2-user/
      delegate_to: app_instance

- name: Deploy App on App Instance
  hosts: app_instance
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy Dockerfile to App Instance
      copy:
        src: Dockerfile
        dest: /home/ec2-user/Dockerfile

    - name: Build Docker image
      docker_image:
        name: hello-app
        build:
          path: /home/ec2-user/
          dockerfile: /home/ec2-user/Dockerfile

    - name: Run Docker container
      docker_container:
        name: hello-app-container
        image: hello-app
        state: started
        ports:
          - "8080:8080"
