- name: Deploy Java application on AWS instance
  hosts: app_instance
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started

    - name: Build Docker image
      docker_image:
        path: "{{ playbook_dir }}"
        name: java_app
        buildargs:
          WAR_FILE: target/hello-1.0.war

    - name: Run Docker container
      docker_container:
        name: java_app
        image: java_app
        ports:
          - "8080:8080"
