- name: Setup instance1
  hosts: instance1
  gather_facts: yes
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install Java and Maven
      apt:
        name: ['openjdk-11-jdk', 'maven']
        state: present

    - name: Clone repository
      git:
        repo: 'https://github.com/vir2ozz/certask.git'
        dest: '/home/ubuntu/certask'

    - name: Build the project
      command: mvn clean install
      args:
        chdir: '/home/ubuntu/certask'

    - name: Fetch the built artifact
      fetch:
        src: '/home/ubuntu/certask/target/hello-1.0.war'
        dest: './hello-1.0.war'
        flat: yes

- name: Setup instance2
  hosts: instance2
  gather_facts: yes
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install Docker
      apt:
        name: ['docker.io']
        state: present

    - name: Copy WAR file to instance2
      copy:
        src: './hello-1.0.war'
        dest: '/home/ubuntu/hello-1.0.war'

    - name: Copy Dockerfile to instance2
      copy:
        src: './Dockerfile'
        dest: '/home/ubuntu/Dockerfile'

    - name: Build Docker image
      command: docker build -t hello-app .
      args:
        chdir: '/home/ubuntu'

    - name: Run Docker container
      command: docker run -d --name hello-app -p 8080:8080 hello-app
