- name: Deploy Java Application
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Copy WAR file
      ansible.builtin.copy:
        src: hello-1.0.war
        dest: /app/hello-1.0.war

    - name: Copy Dockerfile
      ansible.builtin.copy:
        src: Dockerfile
        dest: /app/Dockerfile

    - name: Build Docker image
      ansible.builtin.command:
        chdir: /app
        cmd: docker build -t my-java-app .

    - name: Run Docker container
      ansible.builtin.docker_container:
        name: my-java-app
        image: my-java-app
        state: started
        published_ports:
          - "8080:8080"
