- name: Deploy Java application
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Build Docker image
      docker_image:
        build:
          path: ./
          dockerfile: certask/Dockerfile
        name: hello_app
        source: build

    - name: Deploy application container
      docker_container:
        name: hello_app
        image: hello_app
        state: started
        ports:
          - "8080:8000"
