- name: Build Java application and transfer war file
  hosts: tag_Name_instance1
  become: yes
  tasks:
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present
    - name: Clone Java application repository
      ansible.builtin.git:
        repo: 'https://github.com/vir2ozz/certask.git'
        dest: '/home/jenkins/certask'
    - name: Install Maven
      ansible.builtin.apt:
        name: maven
        state: present
    - name: Build Java application with Maven
      ansible.builtin.command:
        cmd: mvn package
        chdir: /home/jenkins/certask
    - name: Transfer war file to instance2
      ansible.builtin.synchronize:
        src: '/home/jenkins/certask/target/hello-1.0.war'
        dest: '/home/jenkins/hello-1.0.war'
        mode: push
      delegate_to: "{{ groups['tag_Name_instance2'][0] }}"

- name: Build Docker image and run container
  hosts: tag_Name_instance2
  become: yes
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
    - name: Install Docker Python SDK
      ansible.builtin.pip:
        name: docker
    - name: Copy Dockerfile
      ansible.builtin.copy:
        src: /path/to/your/Dockerfile
        dest: /home/jenkins/Dockerfile
    - name: Build Docker image
      ansible.builtin.docker_image:
        build:
          path: /home/jenkins
        name: hello-app
        source: build
    - name: Run Docker container
      ansible.builtin.docker_container:
        name: hello-app-container
        image: hello-app
        state: started
        ports:
          - "8080:8080"
