- name: Build and Deploy Java App
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Create Docker network
      docker_network:
        name: app-network
        state: present

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ playbook_dir }}"
          dockerfile: Dockerfile
        name: java_app
        source: build

    - name: Deploy Docker container
      docker_container:
        name: java_app
        image: java_app
        state: started
        recreate: yes
        exposed_ports:
          - "8080"
        networks:
          - name: app-network
