- name: Build Java application and transfer war file
  hosts: instance1
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install Java and Maven
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - openjdk-8-jdk
        - maven

    - name: Clone repository
      git:
        repo: https://github.com/vir2ozz/certask.git
        dest: /home/ubuntu/certask

    - name: Build Java application
      command: mvn clean package
      args:
        chdir: /home/ubuntu/certask

    - name: Transfer war file to instance2
      synchronize:
        src: /home/ubuntu/certask/target/hello-1.0.war
        dest: /home/ubuntu/

- name: Build Docker image and run container
  hosts: instance2
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Create Dockerfile
      copy:
        content: |
          FROM tomcat:9.0
          COPY hello-1.0.war /usr/local/tomcat/webapps/
        dest: /home/ubuntu/Dockerfile

    - name: Build Docker image
      command: docker build -t hello:1.0 .

    - name: Run Docker container
      command: docker run -d -p 8080:8080 hello:1.0
