- name: Build Java application
  hosts: instance1
  become: yes
  gather_facts: no
  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Clone the Git repository
      git:
        repo: 'https://github.com/vir2ozz/certask.git'
        dest: '/opt/certask'

    - name: Build the Java application
      command: './mvnw package'
      args:
        chdir: '/opt/certask'

    - name: Fetch the built WAR file
      fetch:
        src: '/opt/certask/target/hello-1.0.war'
        dest: 'hello-1.0.war'

- name: Deploy Java application on Docker
  hosts: instance2
  become: yes
  gather_facts: no
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Create a Docker network
      docker_network:
        name: app-network

    - name: Copy Dockerfile
      copy:
        src: Dockerfile
        dest: /tmp/Dockerfile

    - name: Copy WAR file to remote instance
      copy:
        src: hello-1.0.war
        dest: /tmp/hello-1.0.war

    - name: Build Docker image
      docker_image:
        path: /tmp
        name: hello-java-app
        source: build

    - name: Run Docker container
      docker_container:
        name: hello-java-container
        image: hello-java-app
        state: started
        network_mode: app-network
        exposed_ports:
          - "8080"
        published_ports:
          - "8080:8080"
